on: [push, pull_request]

name: test

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.40.0
      - run: deno fmt
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: test.ts
