on: [push, pull_request]

name: test

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.40.0
      - run: deno fmt
      - uses: andymckay/append-gist-action@master
        with:
          gistURL: "https://gist.github.com/ronhippler/11330855c907ea17aa6b287eb8f869d9"
          token: $TOKEN
          file: "test.ts"
          suffix: $matrix.os
