on: [push, pull_request]

name: test

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.40.0
      - run: deno fmt --check
      - run: deno fmt
        if: always()
      - run: deno fmt --check
        if: always()
      - run: mkdir ${{ matrix.os }}
        if: always()
      - run: mv test.ts ${{ matrix.os }}/test.ts
        if: always()
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: artifact
          path: .
